### ISSUE TITLE
Is `intervaltree.at(pt)` upper bound inclusive?

### ISSUE THREAD

**Issue by hongyuchen1030** [chaimleib/intervaltree#128]
So I used the following intervals to build the tree
```python
intervals = [[-0.351  0.        ],
                    [0.         0.1745], 
                    [-1.75    0.75],
]

tree = IntervalTree(intervals )
```

And then I want to find all intervals that overlaps with `0`
```python
res = tree.at(0)
```
It will only return the intervals `[0.         0.1745], [-1.75    0.75]`, and the first interval that has `0` as its maximum will not return.

Is the `intervaltree.at(pt)` not upper bound inclusive? And if so, how to get an upper-bound inclusive query result? Thanks

**Comment by chaimleib** [comment]
All intervals in intervaltree are half-open intervals, including the lower bound but not the upper bound. Unless you do some hackery with the internal boundary table, there is no way to quiet on the upper bounds of contained intervals, since the upper bound is not part of the interval's range.

**Comment by chaimleib** [comment]
Welcome!

If you modify `_search_point` without also modifying how the tree is built, traversed and balanced, you may occasionally be missing results.

**Comment by hongyuchen1030** [comment]
Thanks so much for your information. I will take a deeper look into it.

**Comment by dogganon** [comment]
> All intervals in intervaltree are half-open intervals, including the lower bound but not the upper bound.

@chaimleib It would be useful to allow something like `inclusive=(True, False)` to be passed when creating the tree so that the "openness" of intervals is under full control of the end user.

I am building a caching data structure that caches time-series segments, which requires `inclusive=(True, True)`; Without such option I have to make up the upper bound.
