### ISSUE TITLE
Incorrect overlap query behavior for bracket syntax

### ISSUE THREAD

**Issue by standage** [chaimleib/intervaltree#27]
I'm getting empty sets when I try to use the bracket notation for overlap queries, but I get the correct result when using the .search method. See terminal output below. This is on OS X Yosemite with Python 2.7.8.

```
(pydev)[standage@lappy interval-loci] python 
Python 2.7.8 (default, Oct 19 2014, 16:02:00) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from intervaltree import Interval, IntervalTree
>>> it = IntervalTree()
>>> it.addi(1, 3, "dude")
>>> it.addi(2, 4, "sweet")
>>> it.addi(6, 9, "rad")
>>> for iobj in it:
...   print it[iobj.begin, iobj.end]
... 
set([])
set([])
set([])
>>> for iobj in it:
...   print it.search(iobj.begin, iobj.end)
... 
set([Interval(6, 9, 'rad')])
set([Interval(1, 3, 'dude'), Interval(2, 4, 'sweet')])
set([Interval(1, 3, 'dude'), Interval(2, 4, 'sweet')])
>>> 
```

**Comment by chaimleib** [comment]
For square bracket notation, use a colon (:) instead of a comma:

    it[iobj.begin, iobj.end]  # not this
    it[iobj.begin: iobj.end]  # this!

Since you used a comma, python basically did this instead of what you wanted:

    my_tuple = (iobj.begin, iobj.end)
    print it[my_tuple]

**Comment by standage** [comment]
Great, this works. Docs at https://pypi.python.org/pypi/intervaltree need updated though.

**Comment by chaimleib** [comment]
Ah, looks like I made the same mistake when writing the docs. I'm making a fix.

**Comment by standage** [comment]
Looks like the docs are updated, thanks!
