### ISSUE TITLE
recursion depth

### ISSUE THREAD

**Issue by paulbrodersen** [chaimleib/intervaltree#3]
When initialising a tree with >50 intervals, the recursion depth of python is reached while balancing the tree. Minimum working example:

``` python
from intervaltree import Interval, IntervalTree
from numpy import sort
from numpy.random import randint

def test_intervaltree(n_intervals):
    tmp = sort(randint(1000, size=2*n_intervals))
    starts = tmp[::2]
    stops = tmp[1::2]
    intervals = zip(starts, stops)
    interval_objs = [Interval(start, stop) for start,stop in intervals]
    tree = IntervalTree(interval_objs)
    return tree

test_interval_tree(10) # returns tree
test_interval_tree(50) # returns RuntimeError
```

**Comment by ltnetcase** [comment]
@chaimleib thanks for the great work of you, but I do wish 0-length intervals be supported in the tree, it's important when an inserted data between two already exist points is required to be involved in the tree.
