### ISSUE TITLE
comparing Intervals may succeed in Python2 but fail in Python3

### ISSUE THREAD

**Issue by chaimleib** [chaimleib/intervaltree#32]
### Effect

Either:
- Intervals may not sort in the same order when porting code between Python 2 and Python 3.
- Intervals that were sortable in Python 2 will raise a TypeError in Python 3.
### Cause

Certain types are no longer comparable in Python3.
### Detail

When sorting Intervals, if two Intervals have the same range and a tiebreaker is needed, the data fields are compared. If the data fields hold non-comparable types, behavior may not be consistent when porting code between Python 2 and Python 3.

**Comment by chaimleib** [comment]
The way that we have been trying to avoid the issue of comparing incomparable objects was to make new ways of distinguishing and sorting them. The idea was to enforce stable sorting, where even if the ranges equal, one Interval will always sort lower than the other. 

The advantage of the above is that during the execution of the program, the relative ordering should not change when we edit the IntervalTree. If two intervals had equal ranges, and one sorted below the other, it should **not** flip and suddenly sort above the other, simply because the tree structure changed and needed to be resorted. Note the "should."

The disadvantage is that if the data field of an interval was modified, this could change the sorting order. This is serious, because it is quite likely that users will want to use dynamic objects in the data field, whose sorting order can therefore change without notice to the IntervalTree. (This is probably part of why Python 3 became more strict about ordering many objects. If so, this is all the more reason not to reinvent sorting.)

If we want to have truly stable sorting, the sorting therefore **cannot** be dependent on dynamic objects in the data field. The most elegant way to guarantee this is to not let sorting depend on the data field at all, and instead rely on the `id()` values of Intervals as tiebreakers where the Interval ranges equal.

This is a backwards-incompatible change, which if implemented, must be postponed to a new major version.

**Comment by chaimleib** [comment]
Now that I look back on this, stable sorting of the data field is not critical to the structure of the tree. I think it's OK to live with unstable sorting. By default, we'll use the built-in sorting in Python 2 and Python 3, and if that fails, have a fallback comparison function.

**Comment by ripopov** [comment]
Current version fails for me when comparison of data fields throws something other than TypeError.

I use intervaltree for gdb scripting, and gdb throws gdb.error instead of TypeError.

**Comment by chaimleib** [comment]
That sounds like a bug in the gdb library. If types don't match, a `TypeError` should be thrown. If something else gets thrown, it sounds like something is wrong with gdb's `__cmp__` method.
