### ISSUE TITLE
Cause segment fault when unpickle a large interval tree

### ISSUE THREAD

**Issue by ChangerLow** [chaimleib/intervaltree#36]
when using pickle.loads(pickle.dumps(tree)) , it ran out a segment fault or  sometimes "RuntimeError: ('maximum recursion depth exceeded'"(in diffrent machines) .  the tree size is about 40000.

Traceback (most recent call last):
  File "./pickle.py", line 56, in <module>
  tree = pickle.loads(tree)
File "/demo/intervaltree/intervaltree.py", line 254, in __init__
    self.top_node = Node.from_intervals(self.all_intervals)
  File "/demo/intervaltree/node.py", line 64, in from_intervals
    node = node.init_from_sorted(sorted(intervals))
  File "/demo/intervaltree/node.py", line 82, in init_from_sorted
    self.left_node = Node.from_intervals(s_left)
  File "/demo/intervaltree/node.py", line 64, in from_intervals
    node = node.init_from_sorted(sorted(intervals))
  File "/demo/intervaltree/node.py", line 82, in init_from_sorted
    self.left_node = Node.from_intervals(s_left)
  File "/demo/intervaltree/node.py", line 64, in from_intervals
    node = node.init_from_sorted(sorted(intervals))
  File "/demo/intervaltree/node.py", line 82, in init_from_sorted
    self.left_node = Node.from_intervals(s_left)
  File "/demo/intervaltree/node.py", line 64, in from_intervals
    node = node.init_from_sorted(sorted(intervals))
  File "/demo/intervaltree/node.py", line 82, in init_from_sorted
    self.left_node = Node.from_intervals(s_left)

it was out of system's recursive limit, but when i try to fix it by set  "sys.setrecursivelimit()" func's  parameter greater,  it may ran out segmentation fault.

**Comment by konstantint** [comment]
A balanced tree should never reach any reasonable recursion limit. This might indicate some bug in the balancing code. It would be nice if you could provide a piece of code that reproduces this bug.

Also, make sure you use the latest version - I remember there were times when there were problems with balancing that were fixed since.

**Comment by ChangerLow** [comment]
ok, here's some test code, it can reproduce the bug, the file "data.txt" is like:
1 3  1 2
4 6 2 4
7 10 4 5
.........

about 40000+ lines.
sorry that can not provide u data.txt detail.

===================================
from intervaltree import IntervalTree, Interval
import cPickle as pickle
import os,sys

def getDataByLine(line):
    line=line.strip('\n')
    dic={}
    items = line.split(" ")
    dic['from'] = int(items[0])
    dic['to'] = int(items[1])
    dic['data1'] = items[2]
    dic['data2'] = items[3]
    return dic

def get_data_from_file():
    f = open("data.txt", "r");
    tree = IntervalTree()
    for line in f:
        dic = getDataByLine(line)
        data = (dic['data1'], dic['data2']);
        tree.addi(dic['from'],dic['to'],data)
    return tree

tree = get_data_from_file()
tree = pickle.loads(pickle.dumps(tree))

result_set = tree.search(1024)
print result_set


from the traceback info,  do u thing maybe caused by the recursive in funciton Node.from_intervals()

**Comment by konstantint** [comment]
Of course it is caused by the recursion in Node.from_intervals() - that's the way the tree is constructed, and it seems that in your case the construction code is not doing the balancing job correctly.

Unfortunately, reproducing the bug by just picking 40k random intervals does not work. E.g. this code works fine on my machine:

    from intervaltree import IntervalTree, Interval
    import cPickle as pickle
    import os,sys,random

    random.seed(1)
    def genintervals():
        for i in range(40000):
            a, b, c, d = [random.randint(1, 1000) for j in range(4)]
            yield min(a, b), max(a, b)+1, (str(c), str(d))

    tree = IntervalTree()
    for a, b, d in genintervals():
        tree.addi(a, b, d)

    tree = pickle.loads(pickle.dumps(tree))

    print len(tree)

Try it - if it somewhy fails on yours, then perhaps you are not using the latest version still? Otherwise, perhaps you could provide your `data.txt`.

**Comment by ChangerLow** [comment]
sorry that i miss some detail. (my fault! :P).  
In my case, any two nodes has no intersection, so ,you cant just pick two number for start and end random.
And every node's range is [start, end] not [start, end), so i fixed some code to fit it (see after a while). 
In some node's range [start, end] ,  start is equal with end . like 4 4 2 5 in data.txt
when i delete the line where start == end , i can run it sucess.

here's the code where i modified to fit my situastion.

intervaltree ➤ diff node.py ~/workspace/demo/intervaltree/node.py
294c294
<             if k.begin <= point < k.end:
---
>             if k.begin <= point <= k.end:
intervaltree ➤ diff interval.py ~/workspace/demo/intervaltree/interval.py
43,46c43,46
<                 (begin <= self.begin < end) or
<                 (begin < self.end <= end) or
<                 (self.begin <= begin < self.end) or
<                 (self.begin < end <= self.end)
---
>                 (begin <= self.begin <= end) or
>                 (begin <= self.end <= end) or
>                 (self.begin <= begin <= self.end) or
>                 (self.begin <= end <= self.end)
60c60
<         return self.begin <= p < self.end
---
>         return self.begin <= p <= self.end
113c113
<         return self.begin >= self.end
---
>         return self.begin > self.end


maybe i  modified the code above roughtly caused some bug unexpected.

**Comment by konstantint** [comment]
I'm pretty sure your modification is what broke the code.

If you need to have intervals `[start, end]` and you have integer endpoints there anyway, simply use the original code but represent each interval as `[start, end+1)`.

**Comment by chaimleib** [comment]
Yes, you are both right. I inserted that code to check for null intervals in order to prevent the error you are seeing. The solution is as konstantint posted. Alternatively, if you absolutely must have zero-width points in your data, you can try using SortedDict from the sortedcontainers package, and perform queries over both IntervalTree for Intervals, and over SortedDict for points.

**Comment by ChangerLow** [comment]
@konstantint  sounds like a good idea , i will try it.
@chaimleib  thanks for your work for interval-tree in python, it is the easiest one to use in python version  i have tried so far. thank u!  :+1:   And i will check the SortedDict for more detail.
I will close this issuse and thank u for ur help! :D
