### ISSUE TITLE
Interval removal breaks this tree

### ISSUE THREAD

**Issue by escalonn** [chaimleib/intervaltree#41]
I ran `chop` on a few thousand `IntervalTree`s, and found that it crashed on several of them. Looking at the library code showed that `remove` failed to find `Interval`s where they were supposed to be. I tested until I found something more consistent.

Here, I add 9 intervals to an empty tree (in sorted order, so I could have used an iterable). Then, I remove the interval in the root node, leaving the tree with a broken node. Trying to remove one of the intervals left under that node then raises a `KeyError`.

```
>>> from intervaltree import IntervalTree
>>> t = IntervalTree()
>>> t.addi(860, 917, 1)
>>> t.addi(860, 917, 2)
>>> t.addi(860, 917, 3)
>>> t.addi(860, 917, 4)
>>> t.addi(871, 917, 1)
>>> t.addi(871, 917, 2)
>>> t.addi(871, 917, 3)
>>> t.addi(961, 986, 1)
>>> t.addi(1047, 1064, 1)
>>> t.addi(1047, 1064, 2)
>>> t.removei(961, 986, 1) # remove root node. t.verify() would fail now
>>> t.removei(871, 917, 3)
Node<871, depth=2, balance=0>
 Interval(860, 917, 1)
 Interval(860, 917, 2)
 Interval(860, 917, 3)
 Interval(860, 917, 4)
<:  Node<871, depth=1, balance=0>
     Interval(871, 917, 1)
     Interval(871, 917, 2)
     Interval(871, 917, 3)
>:  Node<1047, depth=1, balance=0>
     Interval(1047, 1064, 1)
     Interval(1047, 1064, 2)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/intervaltree/intervaltree.py", line 372, in removei
    return self.remove(Interval(begin, end, data))
  File "/usr/lib/python2.7/site-packages/intervaltree/intervaltree.py", line 361, in remove
    self.top_node = self.top_node.remove(interval)
  File "/usr/lib/python2.7/site-packages/intervaltree/node.py", line 211, in remove
    return self.remove_interval_helper(interval, done, should_raise_error=True)
  File "/usr/lib/python2.7/site-packages/intervaltree/node.py", line 248, in remove_interval_helper
    raise KeyError(interval)
KeyError: Interval(871, 917, 3)
```

That's with Python 2.7; the same behavior exists in Python 3.4.

**Comment by escalonn** [comment]
The same test run with debug code uncommented in `IntervalTree.remove` and `Node.remove_interval_helper`:
[debug_output.txt](https://github.com/chaimleib/intervaltree/files/195468/debug_output.txt)

**Comment by escalonn** [comment]
I think the problem is in `pop_greatest_child`:

In our case, when `intervals[7]` is removed, a node needs to be pruned. So its left subtree (shown below) is asked for a replacement node with that method.
```
Node<10, depth=1, balance=0>
 Interval(0, 20, 1)
 Interval(0, 20, 2)
 Interval(10, 20, 1)
```
This is what that method incorrectly returns as the greatest child node.
```
Node<10, depth=2, balance=1>
 Interval(0, 20, 1)
 Interval(0, 20, 2)
>:  Node<10, depth=1, balance=0>
     Interval(10, 20, 1)
```
Why? To create the greatest child node, it computes an expected `x_center`, and passes all intervals overlapping it to `Node.from_intervals`.[\[1\]](https://github.com/chaimleib/intervaltree/blob/30fdc1b46699e6db5f1653d390c541226517e722/intervaltree/node.py#L375) In the following few lines it appears to assume that the created node will have no children. But in our situation, the created node does have a child on the right, so changing its `x_center` on line 379 (from 0 to 10) is dangerous and in this case it breaks the node's invariants.

I'm not sure what the fix is. My best guess so far is that `pop_greatest_child` should not call `Node.from_intervals`, and instead simply initialize the node like this: `child = Node(new_x_center, get_new_s_center())`. I don't fully understand the implications of that change but I'll try and get the tests running and explore it.

**Comment by pkerpedjiev** [comment]
Is this fix going to be merged into a future release?

**Comment by pkerpedjiev** [comment]
Unfortunately, this issue doesn't seem to be completely fixed. I've attached a test file that yields another of the same error (based on @escalonn 's fix fork)

[issue41a_test.txt](https://github.com/chaimleib/intervaltree/files/694995/issue41a_test.txt)

**Comment by escalonn** [comment]
Yes, even with my fork I’ve recently run into problems presenting in the same way (some tree failing in bulk chops). I haven’t spent the time to narrow down why.

**Comment by chaimleib** [comment]
fixed on dev and master branches
