### ISSUE TITLE
Is there a method to get any one overlapping interval from the tree with another interval as argument?

### ISSUE THREAD

**Issue by AA33** [chaimleib/intervaltree#45]
This is more of a usage question than an actual issue with the library.

**Comment by chaimleib** [comment]
You can use the `search()` method with an `Interval` argument. For example:

```python
>>> t = IntervalTree.from_tuples([(1,2), (4,7), (5,9)])
>>> i = Interval(6, 8)
>>> t.search(i)
set([Interval(5, 9), Interval(4, 7)])
```

A some other `IntervalTree` methods can also be called this way.
