### ISSUE TITLE
Feature request: add method to compute the numerical overlap between intervals

### ISSUE THREAD

**Issue by tchajed** [chaimleib/intervaltree#49]
For my use case, I search a tree for intervals overlapping some `interval0`, then add up the actual overlaps with `interval0`. I'm using this function:

```python
def overlap(interval1, interval2):
    # interval2's begin is in interval1
    if interval1.begin <= interval2.begin <= interval1.end:
        return min(interval1.end, interval2.end) - interval2.begin
    # interval1's begin is in interval2
    if interval2.begin <= interval1.begin <= interval2.end:
        return min(interval2.end, interval1.end) - interval1.begin
    return 0
```

This overlap computation is easy to get wrong, so it would be nice if `intervaltree` provided a method to do so (eg, `interval.overlap(other)`) that returned a numerical overlap, or 0 if there is no overlap.

**Comment by tchajed** [comment]
Actually after thinking about it `overlap` can be simplified to:

```python
def overlap(interval1, interval2):
    overlap = min(interval1.end, interval2.end) - \
              max(interval1.begin, interval2.begin)
    return max(0, overlap)
```

where the last `max` can be excluded if the intervals are guaranteed to overlap, or a negative overlap is acceptable for non-overlapping intervals.

**Comment by milonimrod** [comment]
This was actually added in #83
