### ISSUE TITLE
what are allowable formats for data? 

### ISSUE THREAD

**Issue by zfrenchee** [chaimleib/intervaltree#50]
Hello. My data is a list of these:

```
(16857,
  17751,
  ['uc009vjc.1',
   'chr1',
   '-',
   16857,
   17751,
   16857,
   16857,
   2,
   '16857,17232,',
   '17055,17751,',
   nan,
   'uc009vjc.1']),
```
And when I `IntervalTree(intervals)` I get:

```
  File ".../venv/lib/python2.7/site-packages/intervaltree/intervaltree.py", line 246, in __init__
    intervals = set(intervals) if intervals is not None else set()
TypeError: unhashable type: 'list'
```

Is `data` not allowed to be a list?

**Comment by chaimleib** [comment]
`data` is allowed to be a list. The issue here is that with `IntervalTree(intervals)`, the initializer expects an iterable of `Interval` objects. If you have a list of tuples, use this instead:

`tree = IntervalTree.from_tuples(intervals)`

**Comment by zfrenchee** [comment]
Thanks! sorry for not reading the docs a little closer.
