### ISSUE TITLE
Feature request: given a point inside an interval,  get the length point-begin and end-point

### ISSUE THREAD

**Issue by gbonline** [chaimleib/intervaltree#52]
A little completation to Interval class:
if exists the contains_point(point) method, 
add the lengthFromTheBegin(point) and a lengthToTheEnd(point) methods
:-)
Giorgio

**Comment by chaimleib** [comment]
How do you envision behavior of these methods when `point` is either inside or outside the interval?

**Comment by gbonline** [comment]
I admit that I was not precise, but following the need for my project
I needed to know the distances for a point inside between two dates, so since I'm using the class IntervalTree, I looked to see if the Interval class gave me some useful methods and I found only the "contains_point()" method, and I thought it would be useful to have the methods requests
thanks  for the attention
Giorgio

**Comment by chaimleib** [comment]
Since the behavior isn't well-defined over all the possible inputs, I'd rather leave this functionality up to each developer. It is possible to access `interval.begin` and `interval.end`, so finding the distance to each date should be a simple check and subtraction:

```python
def timeSinceBegin(interval, now):
    return now - interval.begin if interval.contains_point(now) else None
```

**Comment by chaimleib** [comment]
please comment if you would like to reopen!
