### ISSUE TITLE
Need to override the function __sizeof__

### ISSUE THREAD

**Issue by Sanghyun-Hong** [chaimleib/intervaltree#54]
To know the total size of a IntervalTree instance, the class implementation should include (or override) the method `__sizeof__`.

**Comment by chaimleib** [comment]
The `__sizeof__` method returns the number of bytes taken up by the object, rather than the number of elements inside. Could you explain what problem you are trying to solve? Can you not use `len(tree)` instead?

**Comment by chaimleib** [comment]
stale
