### ISSUE TITLE
Add support for findings intervals that contain a given interval

### ISSUE THREAD

**Issue by dan-zheng** [chaimleib/intervaltree#57]
Currently, `tree.search()` only supports findings intervals that overlap or are contained by a given interval. However, there is no support for finding intervals that contain a given interval.

This could be added in a straightforward manner by replacing the boolean `strict` option with one that accepts three values (overlap, contain, or contained by).

The code at the end of `search()` could be edited to something like:
```python
# option is a parameter to search() that specifies the search type
if option == 'contains':
    result = set(
        iv for iv in result
        if iv.begin <= begin and iv.end >= end
    )
```

**Comment by chaimleib** [comment]
In v3, I've replaced the `search(iv)` method with three methods:
* `overlap(iv)`
* `envelop(iv)`
* `at(point)`

Does the `envelop(iv)` method work for you?

**Comment by dan-zheng** [comment]
I haven't tested, but `envelop` sounds like it would do the trick.
Cheers!
