### ISSUE TITLE
Add a `strict` option to prevent merging adjacent intervals

### ISSUE THREAD

**Issue by ntezak** [chaimleib/intervaltree#62]
As per your own documentation, the end point of an interval are not considered to be included in the interval.
Furthermore if I evaluate
```python
>>> Interval(1, 2).overlaps(Interval(2, 3))
    False
```
It seems like there already exists a PR for this:
https://github.com/chaimleib/intervaltree/pull/43

I would be happy to add unit tests if that helps getting this merged.

**Comment by chaimleib** [comment]
merged an update to the dev branch
