### ISSUE TITLE
Python3.5 Deprecation Warning

### ISSUE THREAD

**Issue by cjw85** [chaimleib/intervaltree#70]
The methods `IntervalTree.search`, `.begin`, and `.end` can cause deprecation warnings:

    intervaltree/intervaltree.py:806: DeprecationWarning: sorted_dict.iloc is deprecated. Use SortedDict.keys() instead.
    boundary_table.iloc[index] for index in xrange(bound_begin, bound_end)

**Comment by moonso** [comment]
Ok looks like this is fixed in current version on GitHub (v3.0.0) but not in pypi distribution (v2.1.0)

**Comment by sochi** [comment]
There is a comment requesting a new release, https://github.com/chaimleib/intervaltree/issues/71 though nothing seem to be happening about it.

**Comment by chaimleib** [comment]
Fixed in 3.0.0!
