### ISSUE TITLE
Release latest version to PyPI?

### ISSUE THREAD

**Issue by alexandersoto** [chaimleib/intervaltree#71]
Hi! Thanks for building a great library :)

I've run into a bug that was fixed in https://github.com/chaimleib/intervaltree/commit/234ecff490276ded975010f72b42b83e82d79232. Would it be possible to release the latest version to PyPI? The current release on PyPI is version 2.1.0 from 2015. Happy to help in any way.

**Comment by chaimleib** [comment]
Released 3.0.0!

**Comment by alexandersoto** [comment]
Wonderful, thanks!
