### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by garyatpt** [chaimleib/intervaltree#79]
hi,
E:\zephyr>pip install intervaltree
Collecting intervaltree
  Using cached https://files.pythonhosted.org/packages/6b/63/42329a3e503366be2be68384336db308a795516b362437368ddd82d3368f/intervaltree-3.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\gary\AppData\Local\Temp\pip-install-kcs7dz4o\intervaltree\setup.py", line 60, in <module>
        long_description = fh.read()
    UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 5223: illegal multibyte sequence
    !!!>>> This is a RELEASE version <<<!!!

    Version: 3.0.1

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\gary\AppData\Local\Temp\pip-install-kcs7dz4o\intervaltree\

**Comment by missingxin** [comment]
Same issue here.

**Comment by missingxin** [comment]
== here is what i do START ==
$ virtualenv test4intervaltree
Using base prefix '################\\python\\python37'
New python executable in
################\test4intervaltree\Scripts\python.exe
Installing setuptools, pip, wheel...
done.

$ pip install --no-cache-dir --index-url https://test.pypi.org/simple/
--extra-index-url https://pypi.org/simple intervaltree


$ >test4intervaltree\Scripts\activate

(test4intervaltree) $ pip install --no-cache-dir --index-url
https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple
intervaltree
Looking in indexes: https://test.pypi.org/simple/, https://pypi.org/simple
Collecting intervaltree
  Downloading
https://test-files.pythonhosted.org/packages/68/d7/7c283a11a870d207964022f05d1da7ceacb2c0bd78edd728277de96ba740/intervaltree-3.0.1.post1.tar.gz
Collecting sortedcontainers<3.0,>=2.0 (from intervaltree)
  Downloading
https://files.pythonhosted.org/packages/13/f3/cf85f7c3a2dbd1a515d51e1f1676d971abe41bba6f4ab5443240d9a78e5b/sortedcontainers-2.1.0-py2.py3-none-any.whl
Installing collected packages: sortedcontainers, intervaltree
  Running setup.py install for intervaltree ... done
Successfully installed intervaltree-3.0.2 sortedcontainers-2.1.0
== here is what i do END ==

Yey, you fixed it, Thanks man!

Chaim-Leib Halbert <notifications@github.com> 於 2018年12月18日 週二 上午10:27寫道：

**Comment by garyatpt** [comment]
It works now....

E:\zephyr>pip uninstall intervaltree
Uninstalling intervaltree-2.1.0:
  Would remove:
    d:\python\python37\lib\site-packages\intervaltree-2.1.0-py3.7.egg-info
    d:\python\python37\lib\site-packages\intervaltree\*
Proceed (y/n)? y
  Successfully uninstalled intervaltree-2.1.0


E:\zephyr>pip install --no-cache-dir --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple intervaltree
Looking in indexes: https://test.pypi.org/simple/, https://pypi.org/simple
Collecting intervaltree
  Downloading https://test-files.pythonhosted.org/packages/68/d7/7c283a11a870d207964022f05d1da7ceacb2c0bd78edd728277de96ba740/intervaltree-3.0.1.post1.tar.gz
Requirement already satisfied: sortedcontainers<3.0,>=2.0 in d:\python\python37\lib\site-packages (from intervaltree) (2.1.0)
Installing collected packages: intervaltree
  Running setup.py install for intervaltree ... done
Successfully installed intervaltree-3.0.2

**Comment by chaimleib** [comment]
Released in 3.0.2!
