### ISSUE TITLE
Bug when running Interval Tree and Remove

### ISSUE THREAD

**Issue by davemarr621** [chaimleib/intervaltree#96]
Bug: Bug when running Interval Tree and Remove

Using VM here: https://repl.it/@DavidMarr/planesweep3

Error message:
Traceback (most recent call last):  File "main.py", line 139, in <module>    tree.removei(val[1],val[2])  File "/home/runner/.local/share/virtualenvs/python3/lib/python3.8/site-packages/intervaltree/intervaltree.py", line 378, in removei    return self.remove(Interval(begin, end, data))  File "/home/runner/.local/share/virtualenvs/python3/lib/python3.8/site-packages/intervaltree/intervaltree.py", line 366, in remove    raise ValueErrorValueError

Code:

# This script uses plane sweep or sweep line method to calculate the
# maximum overlap of y-intervals; An EVENT list was created from all
# lower left x and lower right x coordinates; An IntervalTree data
# structure was to add the y-intervals at the lower left x (start)
# event point then add to the IntervalTree, check for overlap, produce
# a count then at the lower right x coord remove the y-interval from the
# intervaltree
import random
import matplotlib.pyplot as plt
from matplotlib.pyplot import Rectangle
import timeit
import numpy as np
from matplotlib.collections import PatchCollection
from matplotlib.patches import Rectangle
from intervaltree import Interval, IntervalTree
from mpl_toolkits.axes_grid1.inset_locator import zoomed_inset_axes
from mpl_toolkits.axes_grid1.inset_locator import mark_inset

# Set random seed number
num_seed = 12
random.seed(num_seed)
t1 = timeit.default_timer() # timer

print("Starting ...")
print()
print("Random seed => ", num_seed)
print()
# Number of data points
n = 250000
print("Number of points => ",n)
print()

# Set the width and height offsets of the rectangles
num_width = 2
num_height = 2

# Set the x and y dimensions of the points
x_dimension = 25000
y_dimension = 25000
print("X dimension => ", x_dimension)
print("Y_dimension => ", y_dimension)
print()
# Height and width of rectangles
width = np.full((2,n),num_width) # width of rectangle = 2
height = np.full((2,n),num_height) # height of rectangle = 2

def make_boxes(ax, xdata, ydata, width, height, facecolor='lightgray',
                     edgecolor='None', alpha=0.5):
    # Create list for all the error patches
    errorboxes = []
    # Loop over data points; create box from errors at each point
    for x, y, xe, ye in zip(xdata, ydata, width.T, height.T):
        rect = Rectangle((x - xe[0], y - ye[0]), xe.sum(), ye.sum())
        errorboxes.append(rect)
    # Create patch collection with specified colour/alpha
    pc = PatchCollection(errorboxes, facecolor=facecolor, alpha=alpha,
                         edgecolor=edgecolor)
    # Add collection to axes
    ax.add_collection(pc)

# Create figure and axes
fig, ax, = plt.subplots(1)
#plt.savefig('rectangles.png')

# Create 2d tuple as double (to 2 digits) as x, y
pt_coord = [] # the point
intervals = [] # y intervals: lower left x,y to upper left x,y
ll_xy = [] # lower left coord list
lr_xy =[] # lower right coord list
ll_x_lr_x = [] # list of lower left x and lower right x
# 0 at end means left edge (add to interval tree)
# 1 at end means right edge (remove from interval tree)

#print()
for i in range(n):
    x = round(random.uniform(1,x_dimension),2)
    y = round(random.uniform(1,y_dimension),2)
    pt_coord.append([x,y])

    ll_x = x - num_width
    ll_y = y - num_height
    ul_x = x - num_width
    ul_y = y + num_height
    lr_x = x + num_width
    lr_y = y - num_height
    ur_x = x + num_width
    ur_y = y + num_height
    ll_x_lr_x.append([ll_x,ll_y,ul_y,"0"]) # add lower left x
    ll_x_lr_x.append([lr_x,lr_y, ur_y,"1"]) # add lower right x
    
# Create scatter plot
x_coord = [x1[0] for x1 in pt_coord]
y_coord = [x1[1] for x1 in pt_coord]

plt.xlim(0, x_dimension)
plt.ylim(0, y_dimension)
#plt.figure(0)
plt.scatter(x_coord,y_coord,s=40)
plt.title("# points => " + n.__str__() + " , " + "random seed => " + num_seed.__str__() + ", w => " + num_width.__str__() + ", h => " + num_height.__str__())
plt.savefig('all_points.png')

# Call function to create error boxes
_ = make_boxes(ax, x_coord, y_coord, width, height)

plt.xlim(0, x_dimension)
plt.ylim(0, y_dimension)
plt.figure(1)
plt.scatter(x_coord,y_coord,s=40)
plt.title("# points => " + n.__str__() + " , " + "random seed => " + num_seed.__str__() + ", w => " + num_width.__str__() + ", h => " + num_height.__str__())
plt.savefig('rectangles.png')

# EVENT LIST: list of lower left x AND lower right x, sorted low to high
all_x_sorted = []
all_x_sorted = sorted(ll_x_lr_x)
# print(all_x_sorted)

# the interval tree
tree = IntervalTree()
test_overlap =[]
overlap_count = []
list_overlap_count = []
max_count =[]

# Loop through EVENT (X coords) list
# index, ll_x, ll_y, ul_y, 0 Add y-interval or
# index, lr_x, lr_y, ur_y, 1 remove y-interval
for i, val in enumerate(all_x_sorted): 
    # print (i, ",",val)
    if '0' in val: #add y-interval
      # print("Adding interval")
      tree.addi(val[1],val[2])
      test_overlap = tree[val[1]:val[2]] # test for overlap
      overlap_count = (len(test_overlap))# overlap count
      list_overlap_count.append([overlap_count,val[0],val[1]]) # max count and x coord
      #print("Overlap count => ", list_overlap_count)      

    if '1' in val: # remove y-interval
      #print(tree)
      tree.removei(val[1],val[2])
    
print(list_overlap_count)
max_count = (max(list_overlap_count))
print()
print("Max count => ", max_count)
print()
plt.scatter(max_count[1], max_count[2] + num_height, s=200, facecolors='none', edgecolors='r')
plt.title("# points => " + n.__str__() + " , " + "random seed => " + num_seed.__str__() + ", w => " + num_width.__str__() + ", h => " + num_height.__str__())
fig.suptitle('Max Count, x , y = > ' + max_count.__str__())
plt.savefig('greatest_overlap_point.png')

# Plot insert or enlargement
fig, axins, = plt.subplots(1)
plt.xlim(0, x_dimension)
plt.ylim(0, y_dimension)
plt.figure(1)
plt.scatter(x_coord,y_coord,s=40)
plt.title("# points => " + n.__str__() + " , " + "random seed => " + num_seed.__str__() + ", w => " + num_width.__str__() + ", h => " + num_height.__str__())

fig, ax, = plt.subplots(1)
_ = make_boxes(ax, x_coord, y_coord, width, height)

plt.xlim(0, x_dimension)
plt.ylim(0, y_dimension)
plt.scatter(x_coord,y_coord,s=40)
plt.title("# points => " + n.__str__() + " , " + "random seed => " + num_seed.__str__() + ", w => " + num_width.__str__() + ", h => " + num_height.__str__())

plt.xlabel('{0:.2f} seconds needed for code run'.format(timeit.default_timer() - t1))
fig.suptitle('Max Count, x , y = > ' + max_count.__str__())
plt.scatter(max_count[1], max_count[2] + num_height, s=200, facecolors='none', edgecolors='r')

# Create enlargement plot
# Call function to create error boxes
# plot boxes in main plot window
_ = make_boxes(ax, x_coord, y_coord, width, height)

# plot boxes in inset
axins = zoomed_inset_axes(ax, 2.8, loc=2) # zoom-factor: 2.5, location: upper-left
_ = make_boxes(axins, x_coord, y_coord, width, height)

x1, x2, y1, y2 = max_count[1]-7, max_count[1]+7, max_count[2]-7, max_count[2]+7 # specify the limits
axins.set_xlim(x1, x2) # apply the x-limits
axins.set_ylim(y1, y2) # apply the y-limits
axins.scatter(x_coord,y_coord,s=40)
plt.scatter(max_count[1], max_count[2] + num_height, s=200, facecolors='none', edgecolors='r')
mark_inset(ax, axins, loc1=2, loc2=4, fc="none", ec="0.5")

plt.savefig('zoomed in')

print(tree) # tree should be null
print()
# testing timeit()
print("{0:.2f} seconds needed for code run".format(timeit.default_timer() - t1))

print("Finished...")

**Comment by chaimleib** [comment]
It looks like you attempted to remove an interval that did not exist in the tree. You could either avoid making remove calls for nonexistent intervals, or use the `discard` method instead.

**Comment by davemarr621** [comment]
Very good. Thank you. Could I please ask you to share the code snippet to
implement either the check or the discard, Thanks for your help. Dave.

**Comment by chaimleib** [comment]
`tree.discardi(val[1],val[2])` would remove the interval, and be silent if the interval isn't there.

**Comment by davemarr621** [comment]
Excellent !!! Thank you and I will give it a try. v/r Dave

**Comment by davemarr621** [comment]
I replaced
the "tree.removei(val[1],val[2])" with "tree.discardi(val[1],val[2])" and
works great (no crash). Thank you. v/r Dave
