### ISSUE TITLE
insert and expand

### ISSUE THREAD

**Issue by Char-Aznable** [chaimleib/intervaltree#98]
Is there an easy way to insert an `Interval by` expanding the entire range of an existing `IntervalTree`? For example, given
```python
t = IntervalTree([Interval(1, 10)])
```
doing this `t.insert_expand(Interval(2,3), 'left')` would result in 
```python
IntervalTree([Interval(0,2),Interval(2,3),Interval(3, 10)])
```
while `t.insert_expand(Interval(2,3), 'right')` would result in 
```python
IntervalTree([Interval(1,2),Interval(2,3),Interval(3, 11)])
```
both of which would expand the range by `1`.

**Comment by chaimleib** [comment]
There isn’t a built-in method for this. I think you will need to pull out the intervals, modify them and add them back in.
